#+title: 自动驾驶
#+roam_tags: 汽车 出行 人工智能

* 自动驾驶分级
  L0 级 ：驾驶员完全掌控车辆；
  L1 级 ：自动系统有时能够辅助驾驶员完成某些驾驶任务；
  L2 级辅助驾驶 ：自动系统能够完成某些驾驶任务，但驾驶员需要监控驾驶环境，完成剩余部分，同时保证出现问题，随时进行接管。在这个层级，自动系统的错误感知和判断有驾驶员随时纠正，大多数车企都能提供这个系统。L2 可以通过速度和环境分割成不同的使用场景，如环路低速堵车、高速路上的快速行车和驾驶员在车内的自动泊车；
  L3 级半自动驾驶：自动系统既能完成某些驾驶任务，也能在某些情况下监控驾驶环境，但驾驶员必须准备好重新取得驾驶控制权（自动系统发出请求时）。所以在该层级下，驾驶者仍无法进行睡觉或者深度的休息。在 L2 完成以后，车企的研究领域是从这里延伸的。由于 L3 的特殊性，目前看到比较有意义的部署是在高速 L2 上面做升级；L3 与 L2 的差异是车辆负责周边监控，而人类驾驶员只需要保持注意力以备不时之需。
  L4 级高度自动驾驶：自动系统在某些环境和特定条件下，能够完成驾驶任务并监控驾驶环境；L4 的部署，目前来看多数是基于城市的使用，可以是全自动的代客泊车，也可以是直接结合打车服务来做。这个阶段下，在自动驾驶可以运行的范围内，驾驶相关的所有任务和驾乘人已经没关系了，感知外界责任全在自动驾驶系统，这里就存在着不同的设计和部署思路了；
  L5 级完全自动驾驶：自动系统在所有条件下都能完成的所有驾驶任务。
  
  我们所说的自动驾驶系统（ADS），通常是在 3～5 层级，随着层级的提高，对系统的要求也随之提高。由于目前自动驾驶的分级，特别是 L3 和 L4 处在还没有大规模应用在实际生活之中，我们对待这个需求就存在着一些认知上的争议。
  以上是 SAE 的自动驾驶六级标准，而美国 NHTSA（美国高速公路安全管理局）对自动驾驶的级别主要差异在 L4 和 L5 上，其实就是限定场景和所有场景的区别，NHTSA 的最高级别 L4 已经不限定场景，而 SAE 觉得完全实现自动驾驶和高度自动驾驶，还是应该有一个特定场景差异的。
  
* 应用状况 [2019-01-01]
  目前能在市场出现的乘用车，所能达到的自动驾驶级别最高的也就是 L3，量产上市的主要有特斯拉的部分车型以及奥迪A8，目前很多厂商研发的 L4 级别自动驾驶的技术仍然处于实验测试阶段，距离商用还有一段距离。
