* 目录                                                                  :TOC:
- [[#如何解压-tarxz-文件][如何解压 tar.xz 文件]]
- [[#fixing-gpg-inappropriate-ioctl-for-device-errors][Fixing GPG "Inappropriate ioctl for device" errors]]
- [[#warning-remote-host-identification-has-changed][WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!]]
- [[#配置vnc][配置VNC]]
- [[#如何在ubuntu-1804上安装和配置vnc][如何在Ubuntu 18.04上安装和配置VNC]]
- [[#git-unpacking-objects-卡住][git unpacking objects 卡住]]
- [[#hyper-v-ubuntu-1804-分辨率修改][Hyper-v Ubuntu 18.04 分辨率修改]]

* 如何解压 tar.xz 文件
  #+begin_src shell
    tar xvJf *.tar.xz
  #+end_src
* Fixing GPG "Inappropriate ioctl for device" errors
  from https://d.sb/2016/11/gpg-inappropriate-ioctl-for-device-errors

  #+begin_quote
  Recently I moved all my sites onto a new server. I use Duplicity and Backupninja to perform weekly backups of my server. While configuring backups on the new server, I kept encountering a strange error:

  Error: gpg: using "D5673F3E" as default secret key for signing
  Error: gpg: signing failed: Inappropriate ioctl for device
  Error: gpg: [stdin]: sign+encrypt failed: Inappropriate ioctl for device

  It turns out this error is due to changes in GnuPG 2.1, which only recently landed in Debian Testing. The error occurs because GnuPG 2.1 by default ignores passphrases passed in via environment variables or stdin, and is trying to show a pinentry prompt. "Inappropriate ioctl for device" is thrown because the Backupninja script is not running through a TTY, so there's no way to actually render the prompt.

  To solve the problem, you need to enable loopback pinentry mode. Add this to ~/.gnupg/gpg.conf:

  use-agent
  pinentry-mode loopback

  And add this to ~/.gnupg/gpg-agent.conf, creating the file if it doesn't already exist:

  allow-loopback-pinentry

  Then restart the agent with echo RELOADAGENT | gpg-connect-agent and you should be good to go!
  #+end_quote
* WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!
  known_hosts 文件中删除对应行即可。
* 配置VNC
   https://app.yinxiang.com/fx/cd25fe28-cad7-4495-a2ab-be31db955aa6
* 如何在Ubuntu 18.04上安装和配置VNC
  from https://cloud.tencent.com/developer/article/1350304
  ~/.vnc/xstartup 内容：
  #+begin_src bash
    #!/bin/bash
    xrdb $HOME/.Xresources
    startxfce4 &
  #+end_src
  ~/.bashrc 中加入：
  #+begin_src bash
  alias vncserver='vncserver -geometry 1900x1040'
  #+end_src
* git unpacking objects 卡住
  将拉取地址从https 换成 git。起码可以显示下载进度:)
* Hyper-v Ubuntu 18.04 分辨率修改
  - sudo vim /etc/default/grub
  - GRUB_CMDLINE_LINUX_DEFAULT="quiet splash video=hyperv_fb:1920x1080"
  - sudo update-grub
